
version: "3.9"

services:
  frontend:
    image: rexco-frontend-app
    container_name: rexco-nextjs
    build: .
    restart: always
    ports:
      - "3003:3000"
    env_file:
      - .env.production